compatibility_date = "2022-01-28"
name = "tiny-frontent-api-cloudlare-example"

kv_namespaces = [
    { binding = "TinyFrontendKv", id = "c6ae42f4f3704dddb80dfa4efe243a75", preview_id = "81443b04b2c543f6bcd8305d23d3bf6c" }
]
